//session
export const SET_USER = "SET_USER";

export const SET_RESET_PASSWORD = "SET_RESET_PASSWORD";

export const SET_AUTHENTICATION_LOADING = "SET_AUTHENTICATION_LOADING";
export const SET_AUTHENTICATION_SUCCESS = "SET_AUTHENTICATION_SUCCESS";
export const SET_AUTHENTICATION_ERROR = "SET_AUTHENTICATION_ERROR";